services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  market_data:
    container_name: market_data
    build:
      context: ./services/market_data
    depends_on:
      - redis
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0

  paper_broker:
    container_name: paper_broker
    build:
      context: .
      dockerfile: services/paper_broker/Dockerfile
    depends_on:
      - redis
    ports:
      - "8002:8000"
